---
- hosts: remote
  tasks:
  - name: "sync website"
    synchronize:
      src: site/
      dest: /var/www/naman
      archive: no
      checksum: yes
      recursive: yes
      delete: yes
    become: no